In [3]:
import numpy as np

In [4]:
def mle_dispersal(C, x):
    '''
    MLE dispersal estimate
    
    parameters
    ----------
    C: covariance matrix among sample locations
    x: sample locations
    '''
    
    k = len(C) #number of samples
    Cinv = np.linalg.pinv(C) #inverse of covariance matrix among sample locations
    
    # find MLE MRCA location (eqn 5.6 Harmon book)
    a1 = np.matmul(np.matmul(np.ones(k), Cinv), np.ones(k).reshape(-1,1))
    a2 = np.matmul(np.matmul(np.ones(k), Cinv), x)
    ahat = a2/a1
    
    # find MLE dispersal rate (eqn 5.7 Harmon book)
    xT = x.reshape(-1,1) #make locations a column vector
    R1 = xT - ahat * np.ones(k).reshape(-1,1)
    Rhat = np.matmul(np.matmul(np.transpose(R1), Cinv), R1) / (k-1)
    
    return Rhat[0]

In [5]:
x = np.array([0,1])
t0=1
t1=2
t2=2
t3=1
t4=1

edges

In [10]:
C = np.array([[t0+t2/2, t4/2],[t4/2, t1+t4*(t2+t3)/(2*t2)]])
mle_dispersal(C,x)

array([0.26666667])

nodes

In [11]:
C = np.array([[t0+t2/2, t4/2],[t4/2, t1+t4*(t2+t3)/(2*t2)]])
mle_dispersal(C,x)

array([0.26666667])

paths

In [12]:
C = np.array([[t0+t2, t0, 0],[t0, t0+t3+t4, t4],[0, t4, t1+t4]])
xp = np.array([0,0,1])
mle_dispersal(C,xp)

array([0.13333333])

the two trees

In [13]:
C = np.array([[t0+t2, 0],[0, t1+t4]])
mle_dispersal(C,x)

array([0.16666667])

In [14]:
C = np.array([[t0+t3, 0],[0, t1]])
mle_dispersal(C,x)

array([0.25])

something wrong with the paths approach? once again it is 1/2!

interesting that edges and nodes give dispersal rate larger than largest estimate across trees?